FROM node:12-alpine as builder
WORKDIR /app
COPY ./package*.json ./
COPY ./lerna.json ./
COPY ./packages/bot/package*.json ./packages/bot/
COPY ./packages/lint/package*.json ./packages/lint/
RUN npm ci
RUN npm run bootstrap
COPY ./packages/bot/ ./packages/bot/
COPY ./packages/lint/ ./packages/lint
COPY ./tsconfig.*.json ./
RUN npm run build
EXPOSE 3000
WORKDIR /app/packages/bot
CMD [ "npm", "run", "dev" ]
